### ISSUE TITLE
Error while retrieving result

### ISSUE THREAD

**Issue by jbonjean** [titilambert/joulupukki#5]
The build on a ubuntu 14.04 was successful but it seems joulupukki failed to retrieve the result:

```
Exception in thread 8a14ec0b-00e9-42ce-b8c9-48bb7fadf6e6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/var/builder/joulupukki/joulupukki/worker/builder.py", line 201, in run
    self.run_packer(global_packer_conf, ".")
  File "/var/builder/joulupukki/joulupukki/worker/builder.py", line 168, in run_packer
    if packer.run() is True:
  File "/var/builder/joulupukki/joulupukki/lib/packer.py", line 80, in run
    if step_function() is not True:
  File "/var/builder/joulupukki/joulupukki/lib/debpacker.py", line 150, in get_output
    debs_raw = self.cli.copy(self.container['Id'], "/output")
  File "/var/builder/joulupukki/env/local/lib/python2.7/site-packages/docker/client.py", line 533, in copy
    self._raise_for_status(res)
  File "/var/builder/joulupukki/env/local/lib/python2.7/site-packages/docker/client.py", line 94, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Could not find the file /output in container 2fb63b9f384174354afe7e7e6e3b4ba41b2bbe6e8ea9fa1177d477a3fd4196ae")
```

**Comment by titilambert** [comment]
This should be fixed
